### ISSUE TITLE
Bug: some UVs are messed up?

### ISSUE THREAD

**Issue by jvukovich** [arbruijn/DesLevelObj#4]
Blarget and I were chatting and I converted one of this new levels "Desync".
https://sectorgame.com/dxma/mission/?m=2097

This is what the UVs look like in Descent/Inferno editor:
![image](https://github.com/arbruijn/DesLevelObj/assets/6004664/aacdccee-b77a-40e5-a75b-e2913acf9088)

This is what the UVs look like for the obj file after export:
![image](https://github.com/arbruijn/DesLevelObj/assets/6004664/7d07026d-f78d-4ba7-ba43-349d4495944a)

Looks like some of the UV data is getting messed up. Not sure what, though.

**Comment by arbruijn** [comment]
This looks like a triangulation issue.

It also appears in Inferno when you force a different triangulation by moving a vertex.

I don't know how this can be solved unfortunately. Maybe SaladBadger or ProxyOne knows.

![image](https://github.com/arbruijn/DesLevelObj/assets/1179120/f3541fb3-5041-4a03-8e4f-603b249bbf42)

![image](https://github.com/arbruijn/DesLevelObj/assets/1179120/ce205989-0ae8-4b4b-a657-e6cd54b29f45)

**Comment by Blarget2** [comment]
After you stop moving the vert, the Flipped triangle is consistent and doesn't change between Rebirth variations. That means this behavior is deterministic. There should be a way of determining which way it is stored. The triangle only flips if you bend the quad past planarity. Which side you do it on will determine which way it is triangulated. This is actually true for most 3D engines and modeling programs.

**Comment by arbruijn** [comment]
hm, DesLevelObj could do triangulation itself in the same way Inferno does it, that should help I suppose

**Comment by arbruijn** [comment]
I think it's fixed with this version. Can you check?
[DesLevelObj-1.1.1.zip](https://github.com/arbruijn/DesLevelObj/files/11743789/DesLevelObj-1.1.1.zip)

**Comment by jvukovich** [comment]
Awesome, looks good here! Thanks Arne!

![image](https://github.com/arbruijn/DesLevelObj/assets/6004664/5123cc76-f8cb-4183-b38a-1b509fc9381e)
